
DROP TABLE Check_in_out CASCADE CONSTRAINTS;
DROP TABLE Guest_Reservation_Mapping CASCADE CONSTRAINTS;
DROP TABLE Room_Hotel_Mapping CASCADE CONSTRAINTS;
DROP TABLE Reservation_Details CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Other_Guests CASCADE CONSTRAINTS;
DROP TABLE Order_Hotel_Mapping CASCADE CONSTRAINTS;
DROP TABLE Inventory_Details CASCADE CONSTRAINTS;
DROP TABLE Supplier CASCADE CONSTRAINTS;
DROP TABLE Staff_Role CASCADE CONSTRAINTS;
DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE Room CASCADE CONSTRAINTS;
DROP TABLE Hotel_Service CASCADE CONSTRAINTS;
DROP TABLE Guest CASCADE CONSTRAINTS;
DROP TABLE Hotel CASCADE CONSTRAINTS;
